### ISSUE TITLE
日付の整列

### ISSUE THREAD

**Issue by PiroHiroPiro** [jpazureid/hexo-theme-jpazure#27]
各記事のタイトル、サマリー、タグなどは整列されていますが、日付だけ整列されておりません。
もし意図がなければ、整列されている方がきれいかなと感じました。
一度ご検討いただけますと幸いです。
よろしくお願いいたします。

![image](https://user-images.githubusercontent.com/15605155/103066411-2e8d0100-45fc-11eb-8d72-41e7ea68e146.png)

**Comment by watahani** [comment]
遅くなってすみません、確認しました。検討してみます！

**Comment by watahani** [comment]
#34

**Comment by PiroHiroPiro** [comment]
修正いただき、ありがとうございます！
