### ISSUE TITLE
トレードマーク

### ISSUE THREAD

**Issue by watahani** [jpazureid/hexo-theme-jpazure#5]

**Comment by noishiza** [comment]
GitHub Blog の場合、(2) の例外に当たると判断。なので利用可能。

https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/general.aspx

Microsoft logos cannot be used in a way that might suggest affiliation with Microsoft, including, but not limited to, the account, profile, or header images. The only exceptions to these requirements are if (1) you’ve secured permission from Microsoft through a license or equivalent (though such licenses are not generally available in this context); or **(2) you’re using a Microsoft trademark (not including logos) to describe the purpose of your account, page, or community provided that:

you are not suggesting affiliation with or endorsement by Microsoft; and,
your account does not use the name or likeness of any prominent individuals within Microsoft.**

Microsoft Logo についてはこちらのサイトに詳細要件アリ。
https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/logo.aspx

使うとしたら背景白の以下かな。背景黒のバージョンもあります。
このページも一通り確認しましたが、使用自体は特に問題ないと判断してます。

http://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE2qVsJ?ver=3f74

同ページに余白の入れ方と、最小サイズの記載アリ。

**Comment by kiki-kekat** [comment]
[logo - memo]
The width of the logo must always be at least 72 pixels for on-screen or 1” (25.4 mm) for print, and the height of the logo must always be at least 15.5 pixels for on-screen or .22” (5.5 mm) for print.

[マージ memo]
最小サイズ:
縦: 15.5 + 15.5 + 15.5 = 46.5 px
横: 15.5 + 15.5 + 72 = 103 px

今回のサイズ:
縦: 56 px
横: 124 px

**Comment by watahani** [comment]
#21
